### ISSUE TITLE
关于章节`裸指针小结`的示例代码的疑问

### ISSUE THREAD

**Issue by zzhaolei** [Warrenren/inside-rust-std-library#2]
我本地使用`rustc 1.60.0`试了一下，发现这一段代码是可以编译运行的，[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=60512038793eb3d226868cd43725f8ea)

[章节位置](https://github.com/Warrenren/inside-rust-std-library/blob/main/RUST%E6%A0%87%E5%87%86%E5%BA%93%E5%88%86%E6%9E%90.md#%E8%A3%B8%E6%8C%87%E9%92%88%E5%B0%8F%E7%BB%93)

示例代码:
```
#[repr(packed)]
struct RefTest {a:u8, b:u16, c:u32}
fn main() {
   let test = RefTest{a:1, b:2, c:3};
   //下面代码无法通过编译，因为test.b 内存字节位于奇数，无法用于借用
   let ref1 = &test.b
}
```

**Comment by Warrenren** [comment]
编译会生成告警，告警中详细说明了在未来的版本会是一个hard error,并且解释了问题所在。但这里的确需要改一下

**Comment by Warrenren** [comment]
已经修改了
