### ISSUE TITLE
关于章节 `内存` 的疑问

### ISSUE THREAD

**Issue by a1393323447** [Warrenren/inside-rust-std-library#3]
在第二章 `RUST标准库内存模块代码分析` [裸指针标准库代码分析](https://github.com/Warrenren/inside-rust-std-library/blob/main/02-%E5%86%85%E5%AD%98.md#%E8%A3%B8%E6%8C%87%E9%92%88%E6%A0%87%E5%87%86%E5%BA%93%E4%BB%A3%E7%A0%81%E5%88%86%E6%9E%90) 里的 1、2 点：
> 1. 将 usize 类型数值强制转换成裸指针类型，以此数值为首地址的内存块被转换为相应的类型。这一转换是**不安全**的。
> 2. 在不同的裸指针类型之间进行强制转换，实质上完成了裸指针指向的内存块的类型强转，这一转换是**不安全**的。

这里提到的 `不安全` 是指这两个操作是 `unsafe` 的意思吗？
如果是的话，这个表述是有误的。例如：
```rust
#![allow(unused)]

struct Foo {
    a: i32,
    b: i64,
    c: u8,
}

struct Bar {
    a: i64,
    b: u64,
}

fn main() {
   let foo_ptr = 0usize  as *const Foo;
   let bar_ptr = foo_ptr as *const Bar;
}
```
这段代码是可以[通过编译](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=62b3309334e442bb2f27907334fd9909)的。换句话说，1、2 点提到的操作都是 `safe` 的。

**Comment by a1393323447** [comment]
类似的问题还在同一章中的[裸指针的创建](https://github.com/Warrenren/inside-rust-std-library/blob/main/02-%E5%86%85%E5%AD%98.md#%E8%A3%B8%E6%8C%87%E9%92%88%E7%9A%84%E5%88%9B%E5%BB%BA)中出现：
> 直接用usize的数值创建裸指针：
```rust
{
        let  a: usize = 0xf000000000000000;
        unsafe {a as * const T}
}
```
如：
```rust
#![allow(unused)]

struct Foo {
    a: i32,
    b: i64,
    c: u8,
}

fn cast<T>(addr: usize) -> *const T {
    addr as *const T
}

fn main() {
   let foo_ptr = cast::<Foo>(0);
   let foo = unsafe { & *foo_ptr };
}
```
也是能够[通过编译](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a157082ca89e7b6c8349c8a786755036)的。

**Comment by Warrenren** [comment]
不安全的意思就是直接把内存块转换成了类型，并且在以后可能对内存块按照这个类型进行读写。但内存块是否是这一类型编译器是不知道的，没法检查，所以是不安全。当然，仅仅转换是不会出问题的
